[project]
name = "almacen-agentes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "carlos.Victus", email = "carlosadrian.cancela@rai.usc.es" }
]
requires-python = ">=3.14"
dependencies = [
    "coverage>=7.15.4",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
]

[project.scripts]
almacen-agentes = "almacen_agentes:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
